name: Bucketlist
options:
  bundleIdPrefix: com.bucketlist
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  supabase-swift:
    url: https://github.com/supabase/supabase-swift
    from: 2.0.0
  
targets:
  Bucketlist:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - "**/*.md"
          - "**/*.txt"
          - "**/*.sh"
          - "**/.cursor/**"
          - "**/.git/**"
          - "**/.env"
          - "project.yml"
          - "flutter_app/**"
          - "build/**"
          - "DerivedData/**"
          - ".derivedData/**"
    resources: []
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: Bucketlist
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: supabase-swift
        product: Supabase
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bucketlist.app
        PRODUCT_NAME: Bucketlist
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1" # iPhone only
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_OPTIMIZATION_LEVEL: "-Onone" # Debug optimization
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        GCC_OPTIMIZATION_LEVEL: 0 # Debug optimization
        SWIFT_COMPILATION_MODE: singlefile

