name: Achieva
options:
  bundleIdPrefix: com.achieva
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  supabase-swift:
    url: https://github.com/supabase/supabase-swift
    from: 2.0.0
  
targets:
  Achieva:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - "**/*.md"
          - "**/*.txt"
          - "**/*.sh"
          - "**/*.log"
          - "**/*.png"
          - "**/*.xcodeproj"
          - "**/.cursor/**"
          - "**/.git/**"
          - "**/.env"
          - "project.yml"
          - "flutter_app/**"
          - "build/**"
          - "DerivedData/**"
          - ".derivedData/**"
          - "AchievaUITests/**"
          - "TestResults.xcresult/**"
          - "node_modules/**"
    resources: []
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: Achieva
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies:
      - package: supabase-swift
        product: Supabase
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.achieva.app
        PRODUCT_NAME: Achieva
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1" # iPhone only
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_OPTIMIZATION_LEVEL: "-Onone" # Debug optimization
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        GCC_OPTIMIZATION_LEVEL: 0 # Debug optimization
        SWIFT_COMPILATION_MODE: singlefile

  AchievaUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.achieva.uitests
        TEST_TARGET_NAME: Achieva
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_TESTING_SEARCH_PATHS: YES
    sources:
        - path: AchievaUITests
    dependencies:
      - target: Achieva
      - sdk: XCTest.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.achieva.uitests
        TEST_TARGET_NAME: Achieva

schemes:
  Achieva:
    build:
      targets:
        Achieva: all
        AchievaUITests: all
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - AchievaUITests
    profile:
      config: Release
    run:
      config: Debug
    archive:
      config: Release


